
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 20;
  public static final int SEMI = 29;
  public static final int CONTINUE = 13;
  public static final int ASSMNT_INC = 37;
  public static final int INT = 4;
  public static final int LESS = 32;
  public static final int FOR = 9;
  public static final int MINUS = 19;
  public static final int AND = 22;
  public static final int OR = 23;
  public static final int COMMA = 39;
  public static final int CLASS = 2;
  public static final int EXTERN = 14;
  public static final int PLUS = 18;
  public static final int IF = 7;
  public static final int ID = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 11;
  public static final int GTR = 31;
  public static final int TRUE = 45;
  public static final int error = 1;
  public static final int LEFT_BRKT = 27;
  public static final int MOD = 21;
  public static final int RT_PAREN = 26;
  public static final int BREAK = 12;
  public static final int VOID = 3;
  public static final int ASSMNT = 36;
  public static final int EQ = 30;
  public static final int ERROR = 42;
  public static final int TIMES = 17;
  public static final int RIGHTBRACE = 16;
  public static final int ASSMNT_DEC = 38;
  public static final int ELSE = 8;
  public static final int POINT = 40;
  public static final int NOT_EQ = 35;
  public static final int WHILE = 10;
  public static final int LESS_EQ = 33;
  public static final int LEFTBRACE = 15;
  public static final int FLOAT = 5;
  public static final int RT_BRKT = 28;
  public static final int LEFT_PAREN = 25;
  public static final int LOGIC_NEGATION = 24;
  public static final int FALSE = 46;
  public static final int FLOAT_LITERAL = 44;
  public static final int GTR_EQ = 34;
  public static final int INT_LITERAL = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "VOID",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "EXTERN",
  "LEFTBRACE",
  "RIGHTBRACE",
  "TIMES",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "MOD",
  "AND",
  "OR",
  "LOGIC_NEGATION",
  "LEFT_PAREN",
  "RT_PAREN",
  "LEFT_BRKT",
  "RT_BRKT",
  "SEMI",
  "EQ",
  "GTR",
  "LESS",
  "LESS_EQ",
  "GTR_EQ",
  "NOT_EQ",
  "ASSMNT",
  "ASSMNT_INC",
  "ASSMNT_DEC",
  "COMMA",
  "POINT",
  "ID",
  "ERROR",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "TRUE",
  "FALSE"
  };
}

